### ISSUE TITLE
[Mod compatibility] Dungeons Enhanced 1.3 prevents loot generation of Artifacts while 1.2 works fine.

### ISSUE THREAD

**Issue by Thombias** [BarionLP/DungeonsEnhanced#1]
Hey there, so i noticed in my WIP modpack that i somehow no longer get artifacts from the mod of the same name generating in any loot chests and barrels, so i checked out all the changelogs of my last updated mods and realised this mod changed something about loot in the newest version. Turns out that the "revised loot tables" in mod version 1.3 unfortunately prevent artifacts from generating in all possible loot containers they can generate in.
I have 2 screenshots here from the same modpack but one with mod version 1.2 and one with mod version 1.3 (Notice the seed in the chat is identical)

Mod version 1.2:
![2021-12-18_00 32 10](https://user-images.githubusercontent.com/46842890/146619975-a8f9cbb1-3555-4e6f-bd2b-c6b38142c106.png)

Mod version 1.3:
![2021-12-18_00 28 02](https://user-images.githubusercontent.com/46842890/146619989-212ac887-12b4-48a4-bd60-40a772c00336.png)

Side note: The whoopee cushion is supposed to always generate in the bonus chest.

Would love to see a fix for this because i don't wanna miss out on the better configurability and fixes from version 1.3 ^.^

**Comment by BarionLP** [comment]
I think this is not a problem with dungeons enhanced but I can take a look. Can you send me a list of all mods you're using?

**Comment by Thombias** [comment]
Here's my mod list:
![Modpack Mod List](https://user-images.githubusercontent.com/46842890/146638502-3fa76b08-874a-4210-aaa5-326070152ee6.PNG)

I also did a seperate test with the minimum required mods, so i only have Dungeons Enhanced, Structure Gel API, Artifacts, ExpandAbility and Curios API installed. The issue still persists, see screenshots below. Seed is still the same.

Bonus Chest loot with Dungeons Enhanced 1.2
![DE ver 1 2](https://user-images.githubusercontent.com/46842890/146638767-d44e576a-fc2f-45c6-954d-7454a4496924.png)

Bonus Chest loot with Dungeons Enhanced 1.3
![DE ver 1 3](https://user-images.githubusercontent.com/46842890/146638773-85420d06-c86f-45e7-a2fc-4e1c8bea7bcc.png)

And here's the mod list for the minimum mods test
![Minimum Mod List](https://user-images.githubusercontent.com/46842890/146638623-bcd887e5-d51a-4dde-aa65-c3875256f2b5.PNG)

I'm only providing screenshots from the bonus chest because it has a 100% chance of the item generating, regardless of how high or low the chance for artifacts is being set in the config file. I did test all vanilla structures that can potentially generate other artifacts. (things like village chests, desert temples, spawner dungeons, etc.)
Even when setting the chance of an artifact generating inside a loot chest to 100%, i get absolutely no artifacts generating whatsoever in mod version 1.3, whereas on 1.2 they do generate like they should. Even the underground campsites provided by the Artifacts mod never have artifacts in them while using Dungeons Enhanced 1.3, despite the chance for artifacts being to 100%. Again, going back to mod version 1.2 fixed this.

I really have no idea why this is happening. All i can really do here is reporting this rather unfortunate issue/incompatibility. :(

**Comment by BarionLP** [comment]
Are you using any data pack?

**Comment by Thombias** [comment]
Nope, no datapacks or anything. Just the 5 mods seen in the minimum mod list provided above.

**Comment by BarionLP** [comment]
ok, i have reproduced the bug, hope i can find out why this is happen

**Comment by BarionLP** [comment]
I fixed the problem for 1.17 and 1.16
I'll release a hotfix after I double checked everything

**Comment by Thombias** [comment]
Awesome! Thank you so much for putting in the work to fix this! :)
