### ISSUE TITLE
empty spawners in the castle structure

### ISSUE THREAD

**Issue by stophallucinating** [BarionLP/DungeonsEnhanced#10]
Description: all of the spawners inside the castle structure that i have found was completely empty

Version:
 - Minecraft version: 1.16.5
 - Forge version 36.2.30
 - Structure Gel API version 1.7.8
 - Dungeons Enhanced version 1.6

Screenshot:
![image](https://user-images.githubusercontent.com/41582097/158015268-9abdef97-817e-456b-a10c-4bc1a99cb399.png)

**Comment by BarionLP** [comment]
oh, seems to be a backport issue, since the way spawner works changed in 1.17
