### ISSUE TITLE
Add challenging structures for late game

### ISSUE THREAD

**Issue by stophallucinating** [BarionLP/DungeonsEnhanced#13]
Maybe add some structures that are challenging even for the late game. Because when you are decently geared, like diamond armor with protection 4 and unbreaking 3 and diamond sword with sharpness 4, fire aspect 2, the mobs starts to get kind of easy to deal with (unless you wait and let 20 zombies with axe and sword spawn in a tight area ofc), and with efficiency 4 pickaxe and enough memory of where the spawners are, most of structures will be extremely easy to deal with when you just rush in and destroy all of the spawners, like the tower structure, all of the spawners would be destroyed before barely any mobs has spawned at all. And all of those makes the majority of structures become something like a loot chest with a single zombie protecting it, these factors make the structures feel kind of lame in the mid and late game. Except from the ice pit and castle structure though, they will take sometime, but will still be relatively easy.

**Comment by BarionLP** [comment]
the mod is not finished yet...
we have big plans
