### ISSUE TITLE
game crashes when player joins world

### ISSUE THREAD

**Issue by cojalexandru** [BarionLP/DungeonsEnhanced#14]
**Describe the bug**
The game crashes when the world tries to create a chunk.

https://pastebin.com/BwefRPYz

**Version Info:**
 - Minecraft version:  1.6.5
 - Forge version: 36.2.21
 - Structure Gel API version: 1.7.8
 - Dungeons Enhanced version 1.6

**Additional context**
From my knowledge it looks like you forgot to put a "=" here: https://github.com/BarionLP/DungeonsEnhanced/blob/1.16.5/src/main/java/com/barion/dungeons_enhanced/world/structures/prefabs/DEBaseStructure.java#L99

So instead of `if (minY > maxY) {y = maxY;}` it would be `if (minY >= maxY) {y = maxY;}`
Because if it happens that minY and maxY are equal it would move to the next line and try to do `random.nextInt(maxY - minY)`
which would be `random.nextInt(0)` which is going to throw the error that caused the crash.

**Comment by cojalexandru** [comment]
Also the same thing with the `nextInt()` method can happen at: https://github.com/BarionLP/DungeonsEnhanced/blob/1.16.5/src/main/java/com/barion/dungeons_enhanced/world/structures/prefabs/DEBaseStructure.java#L106

**Comment by BarionLP** [comment]
thanks for reporting and analyzing
I fixed it

**Comment by BarionLP** [comment]
can you send me the seed anyway?

**Comment by cojalexandru** [comment]
> 
Sorry for the late reply!
Sadly I don't have the world anymore.
