### ISSUE TITLE
rejoining superflat world and sometimes normal world crashes game

### ISSUE THREAD

**Issue by Jetpack-Cat** [BarionLP/DungeonsEnhanced#15]
rejoining superflat world and sometimes normal world crashes game. create superflat world, go back to main menu, try to rejoin

**Version Info:**
 - 1.16.5
 - 36.2.31 (but other versions have the same thing happen)
 - 1.78
 - 1.5

https://gist.github.com/Jetpack-Cat/9c8d8d72f42a676b3e3534613f7fa0b2

**Comment by BarionLP** [comment]
duplicate of #14 

update Dungeons Enhanced
