### ISSUE TITLE
Crash when surface is to low for underground structures

### ISSUE THREAD

**Issue by JetpackRescue** [BarionLP/DungeonsEnhanced#16]
**Describe the bug**
Running around, game crashes.

**Version Info:**
 - Minecraft version: 1.16.5
 - Forge version 36.2.31
 - Structure Gel API version 1.7.8
 - Dungeons Enhanced version 1.7

https://gist.github.com/JetpackRescue/1c6cb102fd137e390bb38eac4c416cff

**Comment by BarionLP** [comment]
do you have the seed and the rough location?

**Comment by BarionLP** [comment]
I guess I found it, but this only happens if the surface height is less than 11, which is impossible in with normal generation.

**Comment by JetpackRescue** [comment]
Oh yeah it was a super flat world

**Comment by BarionLP** [comment]
usually our structures shouldn't generate in superflat worlds, that could indicate a broken config file, you could try deleting the current one and let the game generate a new
