### ISSUE TITLE
Crash in superflat world with structure generation turned off in minecraft rules

### ISSUE THREAD

**Issue by Jetpack-Cat** [BarionLP/DungeonsEnhanced#18]
1.16.5 Forge 36.2.33

[crash-2022-04-26_22.05.38-server.txt](https://github.com/BarionLP/DungeonsEnhanced/files/8568984/crash-2022-04-26_22.05.38-server.txt)

**Comment by BarionLP** [comment]
there is a reason why there are issue templates
anyway are you sure you are on the newest version of dungeons enhanced?
