### ISSUE TITLE
The return of dungeon clashing

### ISSUE THREAD

**Issue by Armokthespideroverlord** [BarionLP/DungeonsEnhanced#19]
**Describe the bug**
It seems like dungeons are spawning into one another again with the latest version of this mod, although not nearly as prevalent as before, I have some examples below, keep in mind that in some of these cases other modded dungeons appear to be intersecting as well, the other modded dungeons in question would be from additional structures, artifacts, awesome dungeons and awesome dungeons ocean edition, bygone nether, cloud storage, ecologics, Friends&Foes, quark, the conjurer, valhelsia structures, waystones, and YUNG's better dungeons/better mineshafts/better strongholds/extras

**Version Info:**
 - Minecraft version: 1.18.2
 - Forge version 40.1.2
 - Structure Gel API version 2.2.3
 - Dungeons Enhanced version 3.1

**Screenshots**
![2022-05-03_17 30 29](https://user-images.githubusercontent.com/30275515/166584900-0fe00789-5477-4304-a475-f0d4ddb9ab56.png)
![2022-05-03_18 16 33](https://user-images.githubusercontent.com/30275515/166584919-3d534952-2f39-4c76-b148-81bddbcdea63.png)
![2022-05-03_18 20 01](https://user-images.githubusercontent.com/30275515/166585006-6512294e-3e56-45ac-b63f-f3d8f638803e.png)
![2022-05-03_18 30 39](https://user-images.githubusercontent.com/30275515/166585014-cecc7d16-65f2-43df-b7b9-8ad848e37c28.png)

this last image in particular isn't an example of intersection but does show a dungeon encroaching a bit too close to another one

**Comment by BarionLP** [comment]
1. Image: not from Dungeons Enhanced
2. Image: I can't see the second structure
3. Image: That's a problem
4. Image: both, the monster maze and the mineshafts from Young are too big to fully check if there are other structures nearby.

**Comment by BarionLP** [comment]
I'm closing this issue for now, assuming the third image is just a rare edge case (which can always happen in procedurally generated worlds). If there are more cases I'll take a look at how to prevent them.

**Comment by Armokthespideroverlord** [comment]
> 1. Image: not from Dungeons Enhanced
> 2. Image: I can't see the second structure
> 3. Image: That's a problem
> 4. Image: both, the monster maze and the mineshafts from Yung, are too big to fully check if there are other structures nearby.

ah, I see, in my current playthrough I actually haven't run into any horrific world gen intersections thankfully, so these probably are just edge cases
