### ISSUE TITLE
Server crash when generating structure with terra forged

### ISSUE THREAD

**Issue by FelipeCardona95** [BarionLP/DungeonsEnhanced#2]
Server crash while pre generating the world with the following
 Critical error detected whilst generating Structure dungeons_enhanced:mob_tower

**Version Info:**
 - Minecraft version: 1.16.5
 - Forge version 36.2.19
 - Mod Version 1.3

**Screenshots**

**Additional context**
Crash Report
[crash-2021-12-28_14.32.15-server.txt](https://github.com/BarionLP/DungeonsEnhanced/files/7786148/crash-2021-12-28_14.32.15-server.txt)

**Let me know if this is unrelated to the mod**

**Comment by BarionLP** [comment]
Try updating Forge (36.2.22) and Dungeons Enhanced (1.4). With these versions everything worked. It's also possible that another mod is related to this issue. I only tested Dungeons Enhanced with Terraforged.
