### ISSUE TITLE
Crash in superflat world, default config

### ISSUE THREAD

**Issue by Jetpack-Cat** [BarionLP/DungeonsEnhanced#20]
**Describe the bug**
Started a super flat world, starting walking, crash.

**Version Info:**
 - Minecraft version: 1.16.5
 - Forge version 36.2.33
 - Structure Gel API version 1.7.8
 - Dungeons Enhanced version 1.7

**Additional context**
My config is default, I deleted it and let it regenerate a week ago.

[crash-2022-05-05_21.04.54-server.txt](https://github.com/BarionLP/DungeonsEnhanced/files/8637457/crash-2022-05-05_21.04.54-server.txt)

**Comment by zlainsama** [comment]
I also got this crash when I was testing on a superflat world.

**Comment by BarionLP** [comment]
#18 #16 #11 #14

I know what is causing the crash, but I'm somehow still not able to reproduce it, which makes it impossible to test. 
Is there any mod that could cause structures generate in superflat worlds? By default they should not do that.

**Comment by zlainsama** [comment]
In my case, the crash happened when I used '/locate village' and teleport to it, loading many new chunks at once.

**Comment by BarionLP** [comment]
once the patch is out, let me know if it is fixed
