### ISSUE TITLE
Please reconsider CurseForge third-party distribution setting

### ISSUE THREAD

**Issue by copygirl** [BarionLP/DungeonsEnhanced#22]
Apologies for the lack of a personalized message, but I will be contacting a number of modders today.
Your mod, Dungeons Enhanced, is one of the few that can't be downloaded by third-party launchers and other tools.
With the following GitHub Gist I would like to try changing your mind, and those of other creators.

https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

Thank you for your work! :green_heart:

**Comment by BarionLP** [comment]
Best way to contact us is Discord.

Anyway, I'll discuss that with Valarauko but since there's no particular reason we've disabled third-party distribution, your chances are good.

**Comment by copygirl** [comment]
Unless there's something in particular you might want to discuss (or in the case of other modders, they can't be reached otherwise), I don't think it's necessary for me to join someone's Discord. I did want to try and use issue trackers so there's a public record for anyone wondering the same thing as me. (Discord is not good for discoverability.)

I appreciate you looking into re-enabling this setting.

**Comment by BarionLP** [comment]
we changed it

**Comment by copygirl** [comment]
Thank you very much!
