### ISSUE TITLE
Deep Crypts spawning in the open

### ISSUE THREAD

**Issue by Null-151** [BarionLP/DungeonsEnhanced#27]
Almost all Deep Crypts I've encountered spawn half buried or just plain out in the open, see picture below
![2022-08-27_12 55 23](https://user-images.githubusercontent.com/48291500/187027150-a3783ad5-bc7d-4671-9ae6-06d547666131.png)

Minecraft 1.18.2
Forge 40.1.73
Structure Gel API 2.4.6
Dungeons Enhanced 3.2.1

**Comment by BarionLP** [comment]
you probably just got an unlucky seed
most of them I found generated buried

checking if they are exposed to air would require massive performance
I might find a easier way to reduce the exposed generation of dungeons in the future but for now we have to live with it
