### ISSUE TITLE
Dungeons generating outside

### ISSUE THREAD

**Issue by Inonedn** [BarionLP/DungeonsEnhanced#3]
**Describe the bug**
dungeons can generate outside of the ground

**Version Info:**
 - Minecraft version: 1.18.1
 - Forge version 39.0.20
 - Mod Version 1.18.1 - 3.0b1

**Screenshots**
![2022-01-16_10 06 52](https://user-images.githubusercontent.com/36087299/149665776-9a887299-9fc2-4545-8d17-78d3160b71de.png)

**Comment by BarionLP** [comment]
This can actually happen with any structure. Also the vanilla structures. I could try testing for each jigsaw piece if it is in the air but that would be to performance consuming.
The best option we have is not to generate structures near cliffs, but this doesn't have 100% accuracy.
I'm already working on an improvement for that problem, but as I said it's not possible to completely prevent it.
