### ISSUE TITLE
crash while starting world

### ISSUE THREAD

**Issue by Thunderrock424242** [BarionLP/DungeonsEnhanced#34]
**Describe the bug**
A clear and concise description of what the bug is and how to reproduce it.
crash while starting world
**Version Info:**
 - Minecraft version: [e.g. 1.18.1] 1.20.1
 - Forge version [e.g. 39.0.79] 47.1.3
 - Structure Gel API version [e.g. 2.1.2]  2.13.0
 - Dungeons Enhanced version [e.g. 3.0] 5.0

**Screenshots**
[latest.log](https://github.com/BarionLP/DungeonsEnhanced/files/12405639/latest.log)

**Additional context**
Add any other context about the problem here e. g. in some the world seed and settings might help

**Comment by BarionLP** [comment]
thanks for reporting, this somehow does not happen in my IDE
