### ISSUE TITLE
[Help] No worldgen folder

### ISSUE THREAD

**Issue by Ricenami** [BarionLP/DungeonsEnhanced#36]
Hi this is one of my favorite structure mods, but I'm playing on fabric, so I tried unzipping the jar file to use it as a datapack, but I realized that there isn't a worldgen folder so its not possible for the structures to generate. Is there any way I can make it work as a datapack, if not I completely understand.

Cheers!

rice

**Comment by BarionLP** [comment]
Dungeons Enhanced uses special structure features from Structure Gel so it wont work without.
Your best bet is to use the structure nbt files. Get rid of all Structure Gel specific features (quite a lot, eg. Gel Blocks and Data Handlers). And create the structure configurations using vanilla features.

Structure Gel makes our life way easier but unfortunately also ties us to forge for now.
