### ISSUE TITLE
Structures can spawn below sea level?

### ISSUE THREAD

**Issue by Aceplante2** [BarionLP/DungeonsEnhanced#37]
tall witch hut, but probably others. Not sure if those arches in the background are yours too?

![2024-01-02_13 04 26](https://github.com/BarionLP/DungeonsEnhanced/assets/101857505/40e06c44-f656-4010-9c21-2294a7887e51)

forge 1.20.1

**Comment by BarionLP** [comment]
is this an updated world from 1.19.x?
is there a swamp nearby where the hut could have tried to generate?
the arches are not from us

**Comment by Aceplante2** [comment]
No, started on 1.20.1, I suppose the biome is probably swamp, but the point is it is under water level

**Comment by BarionLP** [comment]
just was confused because it didn't look like a swamp which would be another problem
for the unterwater part, it seems like i forgot to add the water filter after a rewrite (probably the 1.19 port)
I'll release a fix soon
