### ISSUE TITLE
Watch Tower Chest respawn upon re-logging

### ISSUE THREAD

**Issue by RobertHDPotatoes** [BarionLP/DungeonsEnhanced#9]
**Describe the bug**
I am in the process of testing this for multiple structures, but I can confirm that this happens on the "dungeons_enhanced:watch_tower" structure. All loot chests respawn upon quickly leaving and rejoining the world after breaking the chest. For example, if you go to the top of the Watch Tower, break one of the loot chests and pick up all the loot, then log out, when you log back in the loot chest will be there again and it will be filled with the same loot. This is effectively a major dupe glitch. 

To Reproduce:
1: Make a new creative world
2: Locate a Watch Tower
3: Break a loot chest, and pick up all of its contents
4: Log out
5: Log back in
6: The chest will respawn, with all the loot in it again. You can do this infinitely to duplicate whatever was in the chest to begin with. This may work with all other structures, I have only tested it with the Watch Tower atm. This works in survival and creative.

**Version Info:**
 - Minecraft version: 1.16.5
 - Forge version 36.2.28
 - Structure Gel API version 1.7.8
 - Dungeons Enhanced version 1.5

Here is a video demonstration of the issue.
https://www.youtube.com/watch?v=CMNXjbrdoDM

As you can see in the video, you usually have to log out and log back in pretty fast but is still easily replicable. The first time I attempted it in the video, it didn't work (which surprised me, because it happened to me while playing normally, but in that occasion I had broken the chest closer to a minute before logging out and it still respawned) but it seems to work for either chest in the watch tower. I have not confirmed if this happens with other structures.

**Comment by RobertHDPotatoes** [comment]
I tested a few more structures and several more chests and it doesn't happen with those structures. I'm not sure how I found the one structure that has this issue but I apparently might have lol. But I can consistently dupe chests from watch towers.

**Comment by BarionLP** [comment]
Fixed, if no other issue is reported until tomorrow I'll release a patch

**Comment by BarionLP** [comment]
fix is released
